# Generated by Django 2.1.5 on 2020-09-07 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariado', '0002_auto_20200907_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='id_solicitante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividadesSol', to='voluntariado.Persona'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='id_voluntario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividadesVol', to='voluntariado.Persona'),
        ),
    ]
