# Generated by Django 2.1.5 on 2020-09-07 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('fecha', models.DateField()),
                ('realizada', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('dni', models.IntegerField()),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=100)),
                ('administrador', models.BooleanField()),
                ('voluntario', models.BooleanField()),
                ('solicitante', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='actividad',
            name='id_solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividadesSol', to='voluntariado.Persona'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='id_voluntario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividadesVol', to='voluntariado.Persona'),
        ),
    ]
