# Generated by Django 3.1.1 on 2020-09-19 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariado', '0007_persona_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('tu_nombre', models.CharField(max_length=60)),
                ('tu_direccion_de_correo', models.EmailField(max_length=254)),
                ('tu_mensaje', models.TextField(max_length=200)),
            ],
        ),
    ]
