# Generated by Django 2.1.5 on 2020-09-21 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariado', '0008_miusuario'),
        ('voluntariado', '0008_contacto'),
    ]

    operations = [
    ]
