# Generated by Django 2.1.5 on 2020-09-12 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariado', '0004_auto_20200907_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='solicitante',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='voluntario',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
