# Generated by Django 2.1.5 on 2020-09-12 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariado', '0005_auto_20200912_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='contrasenia',
            field=models.CharField(default='usuario', max_length=60),
        ),
    ]
