# Generated by Django 2.1.5 on 2020-09-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariado', '0006_persona_contrasenia'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='usuario',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
    ]
